# Josh Rosen: Generated by this prompt: https://chat.openai.com/share/0538245f-8389-4b5d-9f26-9bca90d44e95

import json
import sys
import os

def read_config(file_path):
    with open(file_path, 'r') as f:
        return json.load(f)

def write_output(output_path, data):
    with open(output_path, 'w') as f:
        json.dump(data, f, indent=4)

def generate_frames(config):
    frames = []
    for animation in config['animations']:
        for i in range(animation['numberOfFrames']):
            frame_data = {}
            
            frame_data['filename'] = f"{animation['name']}.{str(i).zfill(3)}"
            
            x = i * config['spriteCellWidth']
            y = animation['spriteCellRowIndex'] * config['spriteCellHeight']
            
            frame_data['frame'] = {
                'w': config['spriteCellWidth'],
                'h': config['spriteCellHeight'],
                'x': x,
                'y': y
            }
            
            frame_data['anchor'] = {'x': 0.5, 'y': 0.5}
            
            frames.append(frame_data)
    
    return frames

def list_json_files(directory):
    json_files = [f for f in os.listdir(directory) if f.endswith('.json')]
    return json_files

if __name__ == "__main__":
    current_file_path = os.path.abspath(__file__)
    current_directory = os.path.dirname(current_file_path)
    output_directory = current_directory + "/../public/assets/liberated-pixel-cup-characters/atlases"
    input_directory = current_directory + "/../public/assets/liberated-pixel-cup-characters/animations"

    os.makedirs(output_directory, exist_ok=True)

    for config_file in list_json_files(input_directory):
      config = read_config(input_directory + "/" + config_file)

      output_data = {
          'frames': generate_frames(config)
      }
      output_path = output_directory + "/" + os.path.basename(config_file)
      write_output(output_path, output_data)