# Josh Rosen: Generated by this prompt: https://chat.openai.com/share/0538245f-8389-4b5d-9f26-9bca90d44e95
# See https://github.com/sanderfrenken/Universal-LPC-Spritesheet-Character-Generator

import json
import sys
import os
import glob

from PIL import Image

if __name__ == "__main__":
    current_file_path = os.path.abspath(__file__)
    current_directory = os.path.dirname(current_file_path)
    sheet_definitions_file = current_directory + "/../client/public/assets/liberated-pixel-cup-characters/sheet-definitions.json" 

    search_subdirectories = [
        "head/heads/human_male",
        "head/heads/human_female",
        "hair"
    ]

    output_directory_base = current_directory + "/../client/public/assets/liberated-pixel-cup-characters/atlases"
    spritesheets_directory = current_directory + "/../client/public/assets/liberated-pixel-cup-characters/spritesheets"
    profile_icons_directory = current_directory + "/../client/public/assets/liberated-pixel-cup-characters/profile-icons"
    
    os.makedirs(profile_icons_directory, exist_ok=True)

    for search_subdirectory in search_subdirectories:
        search_directory = spritesheets_directory + "/" + search_subdirectory
        print("search_directory", search_directory)

        for input_filepath in glob.iglob(search_directory + '/**/*.png', recursive=True):
            print("search_directory", search_directory)
            print("input_filepath", input_filepath)
            profile_icon_filepath = input_filepath.replace(spritesheets_directory, profile_icons_directory)
            print("profile_icon_filepath", profile_icon_filepath)
            os.makedirs(os.path.dirname(profile_icon_filepath), exist_ok=True)

            # Load the original image
            img = Image.open(input_filepath)
            
            input_width, input_height = img.size

            if input_width != 832 or input_height != 1344:
                print("skipping image because it does not have dimensions of the LPC 'universal' spritesheets")
                continue

            # Define the X, Y coordinates and the width, height of the square
            x, y, width, height = 16, 133, 32, 32  # Replace these values with your actual coordinates and dimensions

            # Crop the square region from the original image
            cropped_img = img.crop((x, y, x + width, y + height))

            # Save the cropped square to a new PNG file
            cropped_img.save(profile_icon_filepath)
